#!/bin/sh

function help() {
  echo 'Usage: git diffmate [branch]'
  echo 'Opens in textmate all files in a "git diff [branch]" result'
}

REPO_BASE=`git rev-parse --show-toplevel`
if [ 0 -ne $? ]; then
  echo $REPO_BASE
  exit 1
fi

git diff --name-only $@ | awk -v DIR=$REPO_BASE '{print "open txmt://open?url=file://" DIR "/" $0}' | sh
