#!/usr/bin/perl

# create a random password 10 characters long

$password_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz0123456789!@#$%^&*-_";
#$password_chars = "ABCDEFGHIJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz123456789-_";

open RANDOM, "/dev/random";
for ($i = 0; $i < 10; $i++) {
    read RANDOM, $random_chars, 1;
    print substr($password_chars, ord($random_chars) % length($password_chars), 1);
}
close RANDOM ;

print "\n";
